#!/usr/bin/env python3
"""Generate Unreal data tables and the human-readable world catalog.

Pure Python — no Blender, no Unreal. Run it anywhere:

    python3 scripts/gen_data.py

Writes:
    build/unreal/DT_Worlds.csv          world roster + rules, Unreal DataTable
    build/unreal/DT_Interactables.csv   every discoverable object, in uu
    build/markers/<world>.json          per-world marker transforms, in uu
    WORLDS.md                           the readable catalog for the team

The Blender blockout and the Unreal data come from the same source file, so a
world can never drift between the two.
"""

import csv
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))
sys.path.insert(0, os.path.join(ROOT, "blender"))

from world_data import WORLDS  # noqa: E402

M = 100.0  # metres -> Unreal units


def uu(loc):
    """Blender metres (right-handed, +Y forward) -> Unreal units (left-handed)."""
    return [round(loc[0] * M, 2), round(-loc[1] * M, 2), round(loc[2] * M, 2)]


def row_id(world_id, name):
    safe = "".join(c if c.isalnum() else "_" for c in name).strip("_")
    return f"{world_id}__{safe}"


def write_worlds_csv(path):
    with open(path, "w", newline="") as handle:
        w = csv.writer(handle)
        w.writerow(["Name", "DisplayName", "Tagline", "Kind", "Source",
                    "Gravity", "Combat", "PvP", "Vehicles",
                    "GroundSizeUU", "PortalLocationUU", "InteractableCount",
                    "StructureCount"])
        for key, world in WORLDS.items():
            rules = world["rules"]
            ground = world.get("ground")
            w.writerow([
                key, world["name"], world["tagline"], world["kind"],
                world.get("source", "GDD"),
                rules.get("gravity", 1.0), rules.get("combat", False),
                rules.get("pvp", False), rules.get("vehicles", False),
                f"{ground['size'][0] * M:.0f}x{ground['size'][1] * M:.0f}" if ground else "none",
                "|".join(str(v) for v in uu(world["portal"])),
                len(world["interactables"]), len(world["structures"]),
            ])
    return path


def write_interactables_csv(path):
    with open(path, "w", newline="") as handle:
        w = csv.writer(handle)
        w.writerow(["Name", "World", "DisplayName", "LocationUU", "Prompt",
                    "Behaviour", "Secret", "RepeatBehaviour", "RequiresTwoPlayers"])
        for key, world in WORLDS.items():
            for thing in world["interactables"]:
                w.writerow([
                    row_id(key, thing["name"]), key, thing["name"],
                    "|".join(str(v) for v in uu(thing["at"])),
                    thing["prompt"], thing["does"],
                    thing.get("secret") or "", thing.get("repeat") or "",
                    "true" if thing.get("coop") else "false",
                ])
    return path


def write_markers(directory):
    written = []
    for key, world in WORLDS.items():
        markers = [{"name": "PORTAL_Arrival", "kind": "Portal",
                    "location_uu": uu(world["portal"]),
                    "note": "Arrival point and ejection portal origin."}]
        for thing in world["interactables"]:
            markers.append({
                "name": f"INT_{row_id(key, thing['name']).split('__', 1)[1]}",
                "kind": "Interactable",
                "location_uu": uu(thing["at"]),
                "note": thing["does"],
                "coop": bool(thing.get("coop")),
            })
        path = os.path.join(directory, f"{key}.json")
        with open(path, "w") as handle:
            json.dump({"world": key, "display_name": world["name"],
                       "units": "unreal_cm", "markers": markers}, handle, indent=2)
        written.append(path)
    return written


def write_catalog(path):
    total_i = sum(len(w["interactables"]) for w in WORLDS.values())
    total_s = sum(len(w["structures"]) for w in WORLDS.values())
    lines = [
        "# World catalog", "",
        "*Generated by `scripts/gen_data.py` — edit "
        "`blender/world_data.py`, not this file.*", "",
        f"**{len(WORLDS)} spaces · {total_i} discoverable objects · "
        f"{total_s} blockout structures**", "",
        "Every object below is a real entry in the data: it has a position, a "
        "prompt, a behaviour, and where it earns one, a secret and a reason to "
        "come back. Grey-box it with the Blender builder, walk it, then art it.",
        "",
    ]
    for key, world in WORLDS.items():
        rules = world["rules"]
        lines += [
            f"## {world['name']}", "",
            f"*{world['tagline']}*", "",
            f"`{key}` · {world['kind']} · source: {world.get('source', 'GDD')}", "",
            f"- **Gravity** {rules.get('gravity', 1.0)} · "
            f"**Combat** {rules.get('combat', False)} · "
            f"**PvP** {rules.get('pvp', False)} · "
            f"**Vehicles** {rules.get('vehicles', False)}",
            f"- **Blockout** {len(world['structures'])} structures"
            + (f", ground {world['ground']['size'][0]}x{world['ground']['size'][1]} m"
               if world.get("ground") else ", no ground (open space)"),
            "",
            "| Object | Prompt | What it does | Rewards a second look |",
            "|---|---|---|---|",
        ]
        for thing in world["interactables"]:
            extra = thing.get("secret") or thing.get("repeat") or ""
            coop = " **(2P)**" if thing.get("coop") else ""
            lines.append(f"| {thing['name']}{coop} | {thing['prompt']} | "
                         f"{thing['does']} | {extra} |")
        lines.append("")
    with open(path, "w") as handle:
        handle.write("\n".join(lines))
    return path


def main():
    for sub in ("unreal", "markers"):
        os.makedirs(os.path.join(ROOT, "build", sub), exist_ok=True)
    out = [
        write_worlds_csv(os.path.join(ROOT, "build", "unreal", "DT_Worlds.csv")),
        write_interactables_csv(os.path.join(ROOT, "build", "unreal",
                                             "DT_Interactables.csv")),
        write_catalog(os.path.join(ROOT, "WORLDS.md")),
    ]
    out += write_markers(os.path.join(ROOT, "build", "markers"))
    for path in out:
        print(f"[rm] wrote {os.path.relpath(path, os.path.dirname(ROOT))}")
    print(f"[rm] {len(WORLDS)} worlds, "
          f"{sum(len(w['interactables']) for w in WORLDS.values())} interactables")


if __name__ == "__main__":
    main()
